spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: postgres
  #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
#  default-serialization-format: application/json
server.port: 8080
